[package]
name = "orture"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = "0.26.2"
libc = "0.2.147"
anyhow = "1.0.72"
cfg-if = "1.0.0"
serde = { version = "1.0.216", features = ["derive"] }
bincode = "1.3.3"

[[bin]]
name = "orture"
path = "src/main.rs"
