name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  nomt_test:
    name: NOMT - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo build --verbose --workspace
      - run: cargo test --verbose --workspace
  benchtop_check:
    name: NOMT - check benchtop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo check --verbose --manifest-path=benchtop/Cargo.toml
  loom_rw_pass_cell:
    name: NOMT - loom rw_pass_cell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: RUSTFLAGS="--cfg loom" cargo test rw_pass_cell --release --workspace
  doc:
    name: NOMT - doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo doc --verbose --workspace --document-private-items
